name: pytorch-all
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=10.1
  - cudatoolkit-dev=10.1
  - pytorch-mutex=1.0=cuda*
  - pytorch=1.6
  - torchvision
  - faiss-gpu
  - matplotlib>=3.1.1
  - scipy
  - openmesh-python

