name: pytorch-all
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cuda-nvcc=11.7
  - cuda-libraries-dev=11.7
  - cuda-cccl=11.7
  - pytorch-mutex=1.0=cuda*
  - pytorch<2
  - torchvision
  - faiss-gpu
  - matplotlib>=3.1.1
  - scipy
  - openmesh-python
  - boost-cpp=1.65.1
  - mkl<2023

